export const blogList = [
    {
      id: 1,
      title: 'The rice production process from then to today ',
      category: 'rice',
      subCategory: ['Historical Perspective', 'Modern Techniques', 'Technological Advancements'],
      description:
        "Overview of the evolution in rice cultivation techniques from historical methods to modern, mechanized farming practices.",
      authorName: 'Madarasinghe',
      authorAvatar: '/assets/images/author.jpeg',
      createdAt: 'January 18, 2024',
      cover: '/assets/images/image1.jpg',
      pdfUrl: '/assets/pdf/vee1.pdf',
    },
    {
      id: 2,
      title: 'Tea nursery management',
      category: 'tea',
      subCategory: ['Seedling Cultivation', 'Nursery Care', 'Pest Control'],
      description:
        "Brief guidelines on cultivating tea seedlings, covering soil preparation, seed germination, watering, fertilization, and pest control in the nursery.",
      authorName: 'Madarasinghe',
      authorAvatar: '/assets/images/author.jpeg',
      createdAt: 'January 18, 2024',
      cover: '/assets/images/image10.jpg',
      pdfUrl: '/assets/pdf/tea1.pdf',
    },
    {
      id: 3,
      title: 'Selection of a variety of rice',
      category: 'rice',
      subCategory: ['Genetic Factors', 'Climate-Specific Varieties', 'Soil Preferences'],
      description:
        "Guidance on choosing rice varieties, considering genetic factors, adaptability to climate and soil, and the specific needs of farmers.",
      authorName: 'Madarasinghe',
      authorAvatar: '/assets/images/author.jpeg',
      createdAt: 'January 18, 2024',
      cover: '/assets/images/image3.jpg',
      pdfUrl: '/assets/pdf/vee2.pdf',
    },
    {
      id: 4,
      title: 'Lets identify the varieties of tea',
      category: 'tea',
      subCategory: ['Shape and Size', 'Color Variations', 'Flavor Profiles'],
      description:
        "Quick insights into recognizing tea varieties based on leaf characteristics, color, aroma, taste, and their significance in the tea industry.",
      authorName: 'Madarasinghe',
      authorAvatar: '/assets/images/author.jpeg',
      createdAt: 'January 18, 2024',
      cover: '/assets/images/image7.jpg',
      pdfUrl: '/assets/pdf/tea2.pdf',
    },
    {
      id: 5,
      title: 'Nomenclature of rice varieties',
      category: 'rice',
      subCategory: ['Naming Conventions', 'Regional Naming Practices', 'Indigenous Naming Traditions'],
      description:
        "Exploration of the naming conventions for rice varieties, including scientific and common names, with insights into regional and cultural influences.",
      authorName: 'Madarasinghe',
      authorAvatar: '/assets/images/author.jpeg',
      createdAt: 'January 18, 2024',
      cover: '/assets/images/image6.jpg',
      pdfUrl: '/assets/pdf/vee3.pdf',
    },
    {
      id: 6,
      title: 'Annual report tea research',
      category: 'tea',
      subCategory: ['Research Findings', 'New Cultivation Techniques', 'Sustainable Practices'],
      description:
        "Summary of key findings and innovations from annual tea research reports, including studies on disease resistance, yield improvement, and sustainable practices.",
      authorName: 'Madarasinghe',
      authorAvatar: '/assets/images/author.jpeg',
      createdAt: 'January 18, 2024',
      cover: '/assets/images/image5.jpg',
      pdfUrl: '/assets/pdf/annualreporttea.pdf',
    },
    {
      id: 7,
      title: 'Rice Production Schedule',
      category: 'rice',
      subCategory: ['Pre-Planting Activities', 'Crop Management During Growth', 'Harvesting and Post-Harvest Activities'],
      description:
        "A concise breakdown of the seasonal planning, growth management, harvesting techniques, and post-harvest activities in rice production.",
      authorName: 'Madarasinghe',
      authorAvatar: '/assets/images/author.jpeg',
      createdAt: 'January 18, 2024',
      cover: '/assets/images/image12.jpg',
      pdfUrl: '/assets/pdf/vee4.pdf',
    },
    {
      id: 8,
      title: 'Weather and Crop Planning Guide',
      category: 'weather',
      subCategory: ['Pre-Planting Activities', 'Crop Management During Growth', 'Harvesting and Post-Harvest Activities'],
      description:
        "A comprehensive guide detailing the impact of weather on rice production,covering pre-planting activities, crop management strategies during growth,and efficient harvesting and post-harvest activities.",
      authorName: 'Madarasinghe',
      authorAvatar: '/assets/images/author.jpeg',
      createdAt: 'January 22, 2024',
      cover: '/assets/images/image13.jpg',
      pdfUrl: '/assets/pdf/weather1.pdf',
    },
  ];
  